### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method isBubbleOpen on channel com.adriankohls/bubble_overlay

### ISSUE THREAD

**Issue by michael-ottink** [KohlsAdrian/bubble_overlay#1]
I get the following error from line 63 of bubble_overlay.dart. Do you know why this is happening?

```
E/flutter (31666): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method isBubbleOpen on channel com.adriankohls/bubble_overlay)
E/flutter (31666): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154)
E/flutter (31666): <asynchronous suspension>
E/flutter (31666): #1      BubbleOverlay.openBubble.<anonymous closure> (package:bubble_overlay/bubble_overlay.dart:63)
E/flutter (31666): <asynchronous suspension>
E/flutter (31666):
```
This is the line

`_isOpen = await _platform.invokeMethod('isBubbleOpen') ?? false;`

**Comment by KohlsAdrian** [comment]
Closing as fixed with [this commit](https://github.com/KohlsAdrian/bubble_overlay/commit/8cf30c12548bf9a6dd211a34ad42b69785da3cc6)
